/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oca.project;

/**
 *
 * @author 92017403
 */
public class AssignBonusForm extends javax.swing.JFrame {

    /**
     * Creates new form AssignBonusForm
     */
    public AssignBonusForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgMessage = new javax.swing.JOptionPane();
        lblBonusTitle = new javax.swing.JLabel();
        lblManager = new javax.swing.JLabel();
        lblSubList = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        cboManager = new javax.swing.JComboBox();
        cboSubList = new javax.swing.JComboBox();
        txtBonus = new javax.swing.JTextField();
        btnAssignBonus = new javax.swing.JButton();
        btnCheckBonus = new javax.swing.JButton();
        btnBackBonus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBonusTitle.setBackground(new java.awt.Color(153, 153, 153));
        lblBonusTitle.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        lblBonusTitle.setForeground(new java.awt.Color(102, 204, 255));
        lblBonusTitle.setText("Assign Bonus");

        lblManager.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblManager.setText("Manager:");

        lblSubList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSubList.setText("Subordinates List:");

        lblBonus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBonus.setText("Bonus:");

        cboManager.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboSubList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAssignBonus.setBackground(new java.awt.Color(153, 255, 153));
        btnAssignBonus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssignBonus.setForeground(new java.awt.Color(102, 204, 255));
        btnAssignBonus.setText("Assign Bonus");

        btnCheckBonus.setBackground(new java.awt.Color(153, 255, 153));
        btnCheckBonus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCheckBonus.setForeground(new java.awt.Color(102, 204, 255));
        btnCheckBonus.setText("Check Current Bonus");

        btnBackBonus.setBackground(new java.awt.Color(153, 255, 153));
        btnBackBonus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBackBonus.setForeground(new java.awt.Color(102, 204, 255));
        btnBackBonus.setText("Back");
        btnBackBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackBonusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManager)
                            .addComponent(lblSubList)
                            .addComponent(lblBonus))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboManager, 0, 186, Short.MAX_VALUE)
                            .addComponent(cboSubList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAssignBonus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCheckBonus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblBonusTitle)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBackBonus)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblBonusTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManager)
                    .addComponent(cboManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubList)
                    .addComponent(cboSubList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBonus)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAssignBonus)
                .addGap(18, 18, 18)
                .addComponent(btnCheckBonus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackBonus)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackBonusActionPerformed
        //Goes back to main form and disposes of the current form
        MainForm mainForm = new MainForm();
        mainForm.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackBonusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignBonusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignBonusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignBonusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignBonusForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignBonusForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignBonus;
    private javax.swing.JButton btnBackBonus;
    private javax.swing.JButton btnCheckBonus;
    private javax.swing.JComboBox cboManager;
    private javax.swing.JComboBox cboSubList;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblBonusTitle;
    private javax.swing.JLabel lblManager;
    private javax.swing.JLabel lblSubList;
    private javax.swing.JOptionPane msgMessage;
    private javax.swing.JTextField txtBonus;
    // End of variables declaration//GEN-END:variables
}
