/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oca.project;

/**
 *
 * @author 92017403
 */
public class CreatePaymentsForm extends javax.swing.JFrame {

    /**
     * Creates new form CreatePaymentsForm
     */
    public CreatePaymentsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgMessage = new javax.swing.JOptionPane();
        lblAddPaymentsTitle = new javax.swing.JLabel();
        btnCreateMonthly = new javax.swing.JButton();
        btnCreateFornightly = new javax.swing.JButton();
        btnBackAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAddPaymentsTitle.setBackground(new java.awt.Color(153, 153, 153));
        lblAddPaymentsTitle.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        lblAddPaymentsTitle.setForeground(new java.awt.Color(102, 204, 255));
        lblAddPaymentsTitle.setText("Add Payments");

        btnCreateMonthly.setBackground(new java.awt.Color(153, 255, 153));
        btnCreateMonthly.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreateMonthly.setForeground(new java.awt.Color(102, 204, 255));
        btnCreateMonthly.setText("Create Monthly Payment");

        btnCreateFornightly.setBackground(new java.awt.Color(153, 255, 153));
        btnCreateFornightly.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreateFornightly.setForeground(new java.awt.Color(102, 204, 255));
        btnCreateFornightly.setText("Create Fortnightly Payment");

        btnBackAdd.setBackground(new java.awt.Color(153, 255, 153));
        btnBackAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBackAdd.setForeground(new java.awt.Color(102, 204, 255));
        btnBackAdd.setText("Back");
        btnBackAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateMonthly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateFornightly, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAddPaymentsTitle)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBackAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAddPaymentsTitle)
                .addGap(32, 32, 32)
                .addComponent(btnCreateMonthly)
                .addGap(34, 34, 34)
                .addComponent(btnCreateFornightly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnBackAdd)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAddActionPerformed
       //Goes back to main form and disposes of the current form
        MainForm mainForm = new MainForm();
        mainForm.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatePaymentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatePaymentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatePaymentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatePaymentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatePaymentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackAdd;
    private javax.swing.JButton btnCreateFornightly;
    private javax.swing.JButton btnCreateMonthly;
    private javax.swing.JLabel lblAddPaymentsTitle;
    private javax.swing.JOptionPane msgMessage;
    // End of variables declaration//GEN-END:variables
}
