/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oca.project;

/**
 *
 * @author 92017403
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnOpenAssignBonus = new javax.swing.JButton();
        btnOpenPersonalDetails = new javax.swing.JButton();
        btnOpenCreatePayments = new javax.swing.JButton();
        btnOpenRunReports = new javax.swing.JButton();
        btnCloseMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(153, 255, 153));

        lblTitle.setBackground(new java.awt.Color(153, 153, 153));
        lblTitle.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 204, 255));
        lblTitle.setText("Best IT Payroll");

        btnOpenAssignBonus.setBackground(new java.awt.Color(153, 255, 153));
        btnOpenAssignBonus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpenAssignBonus.setForeground(new java.awt.Color(51, 204, 255));
        btnOpenAssignBonus.setText("Assign Bonus");
        btnOpenAssignBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenAssignBonusActionPerformed(evt);
            }
        });

        btnOpenPersonalDetails.setBackground(new java.awt.Color(153, 255, 153));
        btnOpenPersonalDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpenPersonalDetails.setForeground(new java.awt.Color(102, 204, 255));
        btnOpenPersonalDetails.setText("Personal Details and Contractor Data Entry");
        btnOpenPersonalDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenPersonalDetailsActionPerformed(evt);
            }
        });

        btnOpenCreatePayments.setBackground(new java.awt.Color(153, 255, 153));
        btnOpenCreatePayments.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpenCreatePayments.setForeground(new java.awt.Color(102, 204, 255));
        btnOpenCreatePayments.setText("Create Payments");
        btnOpenCreatePayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenCreatePaymentsActionPerformed(evt);
            }
        });

        btnOpenRunReports.setBackground(new java.awt.Color(153, 255, 153));
        btnOpenRunReports.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpenRunReports.setForeground(new java.awt.Color(102, 204, 255));
        btnOpenRunReports.setText("Run Reports");
        btnOpenRunReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenRunReportsActionPerformed(evt);
            }
        });

        btnCloseMain.setBackground(new java.awt.Color(153, 255, 153));
        btnCloseMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCloseMain.setForeground(new java.awt.Color(102, 204, 255));
        btnCloseMain.setText("Close");
        btnCloseMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lblTitle)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOpenRunReports, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenCreatePayments, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenPersonalDetails)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnCloseMain)
                            .addGap(40, 40, 40))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnOpenAssignBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(95, 95, 95)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(btnOpenAssignBonus)
                .addGap(18, 18, 18)
                .addComponent(btnOpenPersonalDetails)
                .addGap(18, 18, 18)
                .addComponent(btnOpenCreatePayments)
                .addGap(18, 18, 18)
                .addComponent(btnOpenRunReports)
                .addGap(45, 45, 45)
                .addComponent(btnCloseMain)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenAssignBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenAssignBonusActionPerformed
        //Creates and opens the assign bonus form and hides the current form from view
        AssignBonusForm assignBonusForm = new AssignBonusForm();
        assignBonusForm.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnOpenAssignBonusActionPerformed

    private void btnOpenPersonalDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenPersonalDetailsActionPerformed
        //Creates and opens the personal details form and hides the current form from view
        PersonalInfoForm personalInfoForm = new PersonalInfoForm();
        personalInfoForm.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnOpenPersonalDetailsActionPerformed

    private void btnOpenCreatePaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenCreatePaymentsActionPerformed
        //Creates and opens the create payment form and hides the current form from view
        CreatePaymentsForm createPaymentsForm = new CreatePaymentsForm();
        createPaymentsForm.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnOpenCreatePaymentsActionPerformed

    private void btnOpenRunReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenRunReportsActionPerformed
        //Creates and opens the payroll report form and hides the current form from view
        PayrollReportsForm payrollReportsForm = new PayrollReportsForm();
        payrollReportsForm.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnOpenRunReportsActionPerformed

    private void btnCloseMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseMainActionPerformed
        //Closes main form and ends application
        this.dispose();
    }//GEN-LAST:event_btnCloseMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseMain;
    private javax.swing.JButton btnOpenAssignBonus;
    private javax.swing.JButton btnOpenCreatePayments;
    private javax.swing.JButton btnOpenPersonalDetails;
    private javax.swing.JButton btnOpenRunReports;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
